# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e66b9a2b799a612ffb0828ad0e5bd70fbfe8c053decc8189ead46ba105b04f1b3270fbd84f09636d5f78a5318d9c09ac6a0e7a929a1452bbd3af2db363c5dfcb

test:
  secret_key_base: 415ab3885e207bfb69d48e084a7f1ae779e7e6f754b9457a2f6628d6c02ad591eb7039ce5bb7f0b77e7f55c1dcb81a4aab105c42ad815be82949dbfa4db5b941

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
